# Details:
# 	STEP 1: Create an initial ubuntu server version for the 'ssl-factory'
#

# Pull base image.
FROM ubuntu:18.04
# Maintainer
MAINTAINER Rob Lassche <roblassche@yahoo.com>

RUN apt-get update \
	&& apt-get -y dist-upgrade -u \
	&& rm -rf /var/lib/apt/lists/*

